# Generated by Django 3.2.7 on 2021-09-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
